# Add 'label1' to any changes within 'examples' folder or any subfolders
area/docs:
  - docs/**/*
  - ./*.md

area/example:
  - hub/examples/

area/builder:
  - builder/**/*

area/housekeeping:
  - .github/**/*
  - ./.gitignore

area/hub:
  - hub/**/*
