name: CD

on:
  push:
    branches:
      - master

jobs:
  update-docker:
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/hub-status
          path: main/status
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          path: src/jina
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - run: |
          echo ${{ steps.buildx.outputs.platforms }}
          docker login -u ${{ secrets.DOCKERHUB_DEVBOT_USER }} -p ${{ secrets.DOCKERHUB_DEVBOT_TOKEN }}
          pip install -r main/builder/requirements.txt
          cd main
          python builder/app.py --reason "master got pushed" --push
          cd status
          git config user.email "dev-bot@jina.ai"
          git config user.name "Jina Dev Bot"
          git add README.md build-history.json hub-stat.svg
          git commit -qm "chore: update readme and build history" -a
          git show '--stat-count=10' HEAD
          git config --list
        env:
          DOCKERHUB_DEVBOT_USER: ${{ secrets.DOCKERHUB_DEVBOT_USER }}
          DOCKERHUB_DEVBOT_PWD: ${{ secrets.DOCKERHUB_DEVBOT_PWD }}
        timeout-minutes: 20
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/hub-status
          force: true
          directory: main/status/
      - uses: technote-space/toc-generator@v2
        with:
          MAX_HEADER_LEVEL: 3
          FOLDING: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: ''
          TARGET_PATHS: 'README.md'
          COMMIT_MESSAGE: 'chore(docs): update TOC'