name: Jina Hub CD

on:
  push:
    branches:
      - master

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          MAX_HEADER_LEVEL: 3
          FOLDING: false
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          TOC_TITLE: ''
          TARGET_PATHS: '*.md'

  update-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Changed Files Exporter
        id: files
        uses: futuratrepadeira/changed-files@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          for changed_file in ${{ steps.files.outputs.files_created }}; do
            echo "${changed_file}" >> build.tmp
          done
          for changed_file in ${{ steps.files.outputs.files_updated }}; do
            echo "${changed_file}" >> build.tmp
          done
          for changed_file in ${{ steps.files.outputs.files_deleted }}; do
            echo "${changed_file}" >> build.tmp
          done
          cat build.tmp | sed 's/\(.*\)\/.*/\1/' | grep ^hub/ | uniq > build.tmp2
          cat build.tmp2